include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    require_trailing_commas: true

analyzer:
  plugins:
    - custom_lint
  exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'
  errors:
    invalid_annotation_target: ignore