include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    avoid_print: false
    avoid_relative_lib_imports: true
    require_trailing_commas: true
    avoid_annotating_with_dynamic: true
    deprecated_member_use_from_same_package: true
    omit_obvious_local_variable_types: true
    omit_obvious_property_types: true
    prefer_expression_function_bodies: true
    prefer_foreach: true
    unnecessary_async: true
    use_decorated_box: true
    use_null_aware_elements: true
    use_truncating_division: true
    always_use_package_imports: true
    avoid_catching_errors: true
    avoid_returning_null_for_void: true
    avoid_setters_without_getters: true
    avoid_shadowing_type_parameters: true
    avoid_slow_async_io: true
    avoid_single_cascade_in_expression_statements: true
    avoid_type_to_string: true
    avoid_types_as_parameter_names: true
    avoid_types_on_closure_parameters: true
    avoid_unnecessary_containers: true
    avoid_void_async: true
    avoid_web_libraries_in_flutter: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    discarded_futures: true
    empty_catches: true
    empty_statements: true
    empty_constructor_bodies: true
    flutter_style_todos: true
    hash_and_equals: true
    valid_regexps: true
    use_to_and_as_if_applicable: true
    use_named_constants: true
    public_member_api_docs: true
    prefer_if_elements_to_conditional_expressions: false

analyzer:
  plugins:
    custom_lint: true

  exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'
    - 'packages/**/lib/generated/{**/**/*,**/*,*}.dart'
    - 'lib/generated/{**/**/*,**/*,*}.dart'
  errors:
    invalid_annotation_target: ignore

formatter:
  trailing_commas: preserve