name: lundi
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.8.0
description: Lundi - Travel planning helper
dependencies:
  animated_bottom_navigation_bar: ^1.4.0
  cloud_firestore: ^5.6.10
  collection: any
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  dot_navigation_bar: ^1.0.2
  email_validator: ^3.0.0
  fancy_password_field: ^2.0.8
  figma_squircle: ^0.6.3
  firebase_auth: ^5.6.1
  firebase_core: ^3.15.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_sliding_box: ^1.1.5
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.0.0
  go_router: ^15.1.3
  google_fonts: ^6.2.1
  i18n: ^4.2.4
  intl: any
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  validators: ^3.0.0
  wc_form_validators: ^1.2.0
dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.5
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  melos: ^7.0.0-dev.9
  pubspec_dependency_sorter: ^1.0.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  very_good_analysis: ^9.0.0
flutter:
  generate: true
  uses-material-design: true
workspace:
  - packages/shared
  - packages/widgets
  - packages/feature_auth
  - packages/feature_plan
  - packages/feature_home
  - packages/feature_assistant
  - packages/feature_edit
  - packages/feature_map
  - packages/feature_settings
  - packages/app
flutter_intl:
  enabled: true
melos:
  scripts:
    unit_test:
      run: melos exec --dir-exists="test" --fail-fast -- flutter test --no-pub --coverage
      description: Run all Flutter tests in this project.
    build_all:
      run: melos exec -- "dart run build_runner build --delete-conflicting-outputs"
    watch_all:
      run: melos exec -- "dart run build_runner watch --delete-conflicting-outputs"
    upgrade_all:
      run: melos exec --concurrency=1 -- "flutter pub upgrade"
