name: widgets
version: 0.1.0
publish_to: none
environment:
  sdk: ^3.8.0
description: Common reusable widgets for the lundi app.
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.3
  google_fonts: any
  shared:
    path: ../shared
dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: ^1.0.5
resolution: workspace
flutter:
  uses-material-design: true
