name: widgets
version: 0.1.0
publish_to: none
description: Common reusable widgets for the lundi app.
resolution: workspace
environment:
  sdk: "^3.8.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.3
  shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any

flutter:
  uses-material-design: true
