name: feature_home
description: Home feature package
version: 0.1.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: "^3.8.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  riverpod_annotation: ^2.6.1
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  google_fonts: ^6.2.1
  go_router: ^15.1.3
  figma_squircle: ^0.6.3
  animated_bottom_navigation_bar: ^1.4.0
  flutter_sliding_box: ^1.1.5
  intl: any
  shared:
    path: ../shared
  widgets:
    path: ../widgets

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  freezed: ^3.0.6

