// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA1iLqDrRJmuC739JVRhpCAYN0R2aB4Qs',
    appId: '1:268644547055:web:8a747fdd86dc3b5e911e1a',
    messagingSenderId: '268644547055',
    projectId: 'auth-riverpod-kano',
    authDomain: 'auth-riverpod-kano.firebaseapp.com',
    storageBucket: 'auth-riverpod-kano.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-KDKsENfFYqtpBMogT2hEw3aMFhUYyGs',
    appId: '1:835037683540:android:e1633eda3a2daa32dfb2c1',
    messagingSenderId: '835037683540',
    projectId: 'lundi-4261c',
    storageBucket: 'lundi-4261c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBny8xbThzQcJFNS9InimILFFhug6rcROA',
    appId: '1:835037683540:ios:65eb45595366404cdfb2c1',
    messagingSenderId: '835037683540',
    projectId: 'lundi-4261c',
    storageBucket: 'lundi-4261c.firebasestorage.app',
    iosBundleId: 'com.lundi.lundi',
  );

}