name: feature_auth
description: Auth feature package
version: 0.1.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: "^3.8.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  riverpod_annotation: ^2.6.1
  firebase_auth: ^5.6.1
  riverpod_generator: ^2.6.5
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  wc_form_validators: ^1.2.0
  go_router: ^15.1.3
  fancy_password_field: ^2.0.8
  shared:
    path: ../shared

dev_dependencies:
  json_serializable: ^6.9.5
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  freezed: ^3.0.6
