name: feature_auth
version: 0.1.0
publish_to: none
environment:
  sdk: ^3.8.0
description: Auth feature package
dependencies:
  fancy_password_field: ^2.0.8
  firebase_auth: ^5.6.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  go_router: ^15.1.3
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.5
  shared:
    path: ../shared
  wc_form_validators: ^1.2.0
dev_dependencies:
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  pubspec_dependency_sorter: ^1.0.5
resolution: workspace
flutter:
  generate: true
  uses-material-design: true
