name: feature_assistant
version: 0.1.0
publish_to: none
environment:
  sdk: ^3.8.0
description: Plan feature package
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  google_fonts: ^6.2.1
  intl: any
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  shared:
    path: ../shared
dev_dependencies:
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  pubspec_dependency_sorter: ^1.0.5
resolution: workspace
