targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/domain/models/*.dart
      riverpod_generator:
        generate_for:
          include:
            - lib/presentation/providers/*.dart
            - lib/data/repositories/*.dart
            - lib/domain/models/*.dart
            - lib/data/data_source/*.dart
      json_serializable:
        generate_for:
          include:
            - lib/domain/models/*.dart
        options:
          explicit_to_json: true
      mockito:mockito_generator:
        generate_for:
          include:
            - test/**/*_test.dart
