targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/domain/entities/*.dart
            - lib/data/models/*.dart
      riverpod_generator:
        generate_for:
          include:
            - lib/presentation/providers/*.dart
            - lib/data/**/*.dart
            - lib/domain/**/*.dart
      json_serializable:
        generate_for:
          include:
            - lib/domain/models/*.dart
            - lib/data/models/*.dart
        options:
          explicit_to_json: true
