name: feature_select_poi
version: 0.1.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: "^3.8.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.1.0
  riverpod_annotation: ^2.6.1
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  intl: any
  sliding_box: ^0.0.2
  go_router: ^15.1.3
  shared:
    path: ../shared
  flutter_sliding_box: ^1.1.5
  flutter_map: ^8.1.1
  flutter_map_mbtiles: ^1.0.4
  path_provider: ^2.1.5
  latlong2: ^0.9.1

dev_dependencies:
  json_serializable: ^6.9.5
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  freezed: ^3.1.0
  mockito: ^5.4.6
  network_image_mock: ^2.1.1
  flutter_localizations:
    sdk: flutter
  http_mock_adapter: any

flutter_intl:
  enabled: true